#!/usr/bin/perl -w

$filename=shift || die("Usage: $0 <mysqldumpFile> [targetDir [pattern [table]]]\nPattern defaults to '-- Table' but note that it is a regular\n expression so characters like /, ?, * etc.\n need to be escaped if used literally");
$target=shift || '.';
$pat=shift || '-- Table';
$tab=shift || '.';

$pat=qr/$pat/;

open(INP,"<$filename") or die("Can't open file $filename\n");

# Get header
$header='';
while(<INP>)
{
    if(/^$pat/)
    {
        last;
    }
    $header.=$_;
}

# $_ contains the start of a new table
do
{
    ($tablename)=/Table structure for table `(.*?)`/;

    print "$tablename\n";
    $matched=$tablename=~/$tab/;
    if($matched)
    {
        open (OP,">$target/$tablename.sql") or die("Can't open output file $tablename.sql");

        print OP $header;

        print OP $_;
    }

    while(<INP>)
    {
        if(/^$pat/)
        {
            last;
        }
        print OP $_ if $matched;
    }

    close OP if $matched;

    if(eof)
    {
        close INP;
        print "Done\n";
        exit;
    }

}while(1);
